name:                  Tests

on:
  push:
    branches:          [main]
  pull_request:
    branches:          [main]

jobs:
  run_tests:

    runs-on:           ubuntu-latest

    steps:
      - name:          build docker image
        uses:          actions/checkout@v3.0.0
        with:
          fetch-depth: 1
        run:           docker build . --file Dockerfile --tag optsent:latest

      - name:          run testing pipeline
        run:           docker run optsent:latest make test
